import ContentWrapper from "@/app/components/ContentWrapper/ContentWrapper";
import Header from "@/app/components/Header/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NewNoteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <ContentWrapper>
    <Header/>
    {children}
    </ContentWrapper>;
}
