import ContentWrapper from "@/app/components/ContentWrapper/ContentWrapper";
import Footer from "@/app/components/Footer/Footeer";
import Header from "@/app/components/Header/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ListLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <ContentWrapper>
      <Header />    
      {children}
      <Footer />
      </ContentWrapper>
  );
}
